### ISSUE TITLE
Font stack on site

### ISSUE THREAD

**Issue by alfredxing** [mrmrs/colors#17]
The font stack on the site (https://github.com/mrmrs/colors/blob/gh-pages/sass/_wut.scss) is currently just

``` css
body { font-family: avenir, 'avenir next'; }
```

Avenir isn't installed by default on Windows machine, maybe use add `sans-serif` (or `Arial`) to the end of the stack?
