### ISSUE TITLE
Add CSS variables (custom properties)

### ISSUE THREAD

**Issue by iamvdo** [mrmrs/colors#6]
Hey,
Instead of using classes, it will be better to use CSS variables, like so:

```
:root{
     var-bg-aqua:  #7FDBFF;
     var-bg-blue:  #0074D9;
}
```

Maybe it will be cool to add for progressive enhancement ?

**Comment by sandrosc** [comment]
Since CSS variables have gained a lot of support in the meantime, please consider adding them to colors.css.
Example:
```css
* {
    --navy: #001F3F;
    --blue: #0074D9;
    --aqua: #7FDBFF;
    --teal: #39CCCC;
    --olive: #3D9970;
    --green: #2ECC40;
    --lime: #01FF70;
    --yellow: #FFDC00;
    --orange: #FF851B;
    --red: #FF4136;
    --fuchsia: #F012BE;
    --purple: #B10DC9;
    --maroon: #85144B;
    --white: #FFFFFF;
    --silver: #DDDDDD;
    --gray: #AAAAAA;
    --black: #111111;
}
```
